### ISSUE TITLE
[ERROR] [scraper.utilities.parse_configuration]: Could not open the CAZy synonym dictionary

### ISSUE THREAD

**Issue by NaiveLittleTiger** [HobnobMancer/cazy_webscraper#36]
When I try to run python cazy_webscraper.py --classes GTs, and then return error '[scraper.utilities.parse_configuration]: Could not open the CAZy synonym dictionary', Then I  go to diroctory /cazy_webscraper/scraper/utilities/parse_configuration, I am not sure this error means that I should modify __init__.py or cazy_dictionary.json, Can someone help me?

**Comment by HobnobMancer** [comment]
First not is `GTs` will raise errors anyway, it want be an except class - `GT` or `gt` will be.

The error is caused by raising a `FileNotFoundError` in line 290 in `scraper.utilities.parse_configuration`, which is raised because the script can't find the file.
In the /cazy_webscraper/scraper/utilities/parse_configuration dir do you see the `cazy_dictionary.json` file?

**Comment by NaiveLittleTiger** [comment]
Thank you very much. And I do have cazy_dictionary.json file
![image](https://user-images.githubusercontent.com/38722443/118821815-2e163f00-b8ea-11eb-976c-281fd32cacc6.png)
error like this picture, I can't find script `scraper.utilities.parse_configuration`
![image](https://user-images.githubusercontent.com/38722443/118822365-ad0b7780-b8ea-11eb-8a84-43dcb6b833d1.png)

**Comment by HobnobMancer** [comment]
If you update your local installation of `cazy_webscraper`, and it produces the same error message, the error message should now include the path `cazy_webscraper` was using to try and find the `cazy_dictionary.json` file. It looks like something is going wrong in the creation of that path.

**Comment by NaiveLittleTiger** [comment]
I am sorry that I still meet the same problem when I try to run `python cazy_webscraper.py` in Window10 and Centos 7. 
In Linux 
![image](https://user-images.githubusercontent.com/38722443/118918695-b8e84f80-b965-11eb-94af-ff8c2890fa9b.png)
However,` cazy_dictionary.json` does exit in this directory ` /cazy_webscraper/scraper/utilities/parse_configuration`，I open the file `cazy_dictionary.json` to check it, and I don't find any problem in `cazy_dictionary.json` 
![image](https://user-images.githubusercontent.com/38722443/118919538-4aa48c80-b967-11eb-9aa2-9edad109fe7c.png)
![image](https://user-images.githubusercontent.com/38722443/118919577-5a23d580-b967-11eb-9b39-c81ec4a6478b.png)

I also try the other method to install cazy_webscraper, using `conda install -c bioconda cazy_webscraper`,  PackageNotFoundError appeared, So I don't know what to do next

**Comment by HobnobMancer** [comment]
We can't guarantee `cazy_webscraper` will run on any other OS other than those listed under requirements in the README (MacOS and Linux).

Is the exact path in the error message the path to the file? It doesn't look correct to me.

`cazy_webscraper` is not yet integrated with bioconda so that installation method is unlikely to have worked.

When installing `cazy_webscraper` did you use the `-e` flag with pip? Your command should look something like `pip install -e <path_to_dir_containing_setup.py>`. So if you are in the `cazy_webscraper` dir then the command would be `pip install -e .`. If you do not use the `-e` flag pip will not unpackage and install the tool as an executable from the dir within which it is located.

**Comment by NaiveLittleTiger** [comment]
Thank you for your help and patience. I just uninstall and git clone `cazy_webscraper ` again, then I use `pip install -e .` Finally I can run the script ` cazy_webscraper.py `
![image](https://user-images.githubusercontent.com/38722443/119007161-91c06b00-b9c3-11eb-8b29-0efeda5d4bcd.png)
This might be changed , not `python3 install -e .`

**Comment by HobnobMancer** [comment]
No problem, and thanks for spotting the typo! The ReadTheDocs documentation is still in progress so I would recommend using the README as your primary source of info, then the ReadTheDocs doc as supplementary until the release of version 1.

For future reference, you didn't need to clone the repo again, just running pip3 install command would suffice. Pip would automatically over write the old install, and install the tool as a direct executable.
