### ISSUE TITLE
'cazy_webscraper.py' is in 'scraper' directory

### ISSUE THREAD

**Issue by LFLWilson** [HobnobMancer/cazy_webscraper#46]
Thanks for this great tool! I just downloaded it and found I had to move cazy_webscraper.py out of the scraper package folder and into the main directory for the script to run.

**Comment by HobnobMancer** [comment]
Hi! Thanks for using cazy_webscraper and glad you’re finding it useful!

That seems like a weird behaviour. How did you install cazy_webscraper?
Also, what error message and traceback *specifically* were you getting when trying to run cazy_webscraper, before you moved the script cazy_webscraper.py?

**Comment by LFLWilson** [comment]
Perhaps I haven't installed it correctly, I just downloaded everything, extracted, and moved into the cazy-webscraper-master folder. I couldn't see cazy_webscraper.py there, but I found it in scraper, so I ran from the terminal:
`python3 scraper/cazy_webscraper.py --families GT1`
That gave me the following error:
`Traceback (most recent call last):
  File "scraper/cazy_webscraper.py", line 76, in <module>
    from scraper import crawler
ModuleNotFoundError: No module named 'scraper'
`

**Comment by LFLWilson** [comment]
Ah, so sorry, I returned to original state and ran:
`pip3 install -e .`
and it works now! Oops. Sorry to bother. Thanks anyway!

**Comment by HobnobMancer** [comment]
Annoyingly downloading the files doesn't install the package. There's a couple of extra steps to install cazy_webscraper I'm afraid

The [README](https://github.com/HobnobMancer/cazy_webscraper#readme) contains a breif summary of each of the methods of installation (of which there are 3).

For a step-by-step walk through that provides more explanation there is an installation tutorial in the [documentation](https://cazy-webscraper.readthedocs.io/en/latest/installation_tutorials.html), which explains in depth how to get set up on MacOS, Windows and Linux systems.

For the quickest and easiest install then I would recommend using `conda` (if you have conda installed), then you need only run the command: `conda install -c bioconda cazy_webscraper` and it handles *everything*. After that, to use cazy_webscraper from *any* directory you need only call it using `cazy_webscraper` followed by any optional flags.

Alternatively, you can use pip (which you'll very likely have installed if you have Python installed), and then you can use the command `pip3 install cazy_webscraper`. Again, to use cazy_webscraper from *any* directory you need only call it using `cazy_webscraper` followed by any optional flags.

The advantage of using `pip` and `conda` is that they will install `cazy_webscraper` **and** all the packages it requires to operate, and build the necessary paths between its modules and submodules.

If you want to continue on from where you have gotten to, you need to move the script `cazy_webscraper.py` back into the `scraper` directory. Then with the terminal pointed out the main (root) directory using `setuptools` to install cazy_webscraper. This can be done using the following command: `pip3 install -e .` -- don't forget the `-e` flag otherwise the tool won't be installed as an executable and you'll run into no ends of problems! Once that is done, to then use `cazy_webscraper`, you can call it by using `Python3 <path to cazy_webscraper.py> <optional flags>`

**Comment by HobnobMancer** [comment]
Oh no worries that was bad timing on my part! Glad its all working now :)
